# NUMERICAL PYTHON (NUMPY) 

#### JOSE MARTIN SJ. NINOBLA                                                                   
#### 2 ECE - D | September 4, 2024

##### 1. In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
##### ndarray as X_normalized.npy

In [15]:
import numpy as np

#This Creates a random 5x5 ndarray
x = np.random.rand(5, 5)

# This normalizes the ndarray (subtract the mean and divide by the standard deviation)
x_normalized = (x - np.mean(x)) / np.std(x)

# Step 3: Save the normalized ndarray as X_normalized.npy
np.save('x_normalized.npy', x_normalized)

# You can also print the arrays if you want to see the results
print("Original x:\n", x)
print("\nNormalized x:\n", x_normalized)


Original x:
 [[0.33297452 0.47357117 0.30280754 0.9276977  0.05705341]
 [0.60619807 0.32712149 0.04818631 0.56618155 0.15669228]
 [0.77478085 0.65118988 0.48385215 0.79322054 0.69490032]
 [0.36912327 0.87159501 0.45125006 0.68887017 0.51008179]
 [0.1660147  0.44678139 0.00730571 0.89267346 0.30003209]]

Normalized x:
 [[-0.5380004  -0.0091592  -0.65147068  1.69899541 -1.57585194]
 [ 0.48970451 -0.56001603 -1.60920469  0.33918611 -1.20106959]
 [ 1.12381295  0.65893703  0.02951174  1.19317213  0.82334976]
 [-0.40203026  1.48797037 -0.09311799  0.80066791  0.12817208]
 [-1.16600421 -0.10992645 -1.76297328  1.56725502 -0.66191029]]


#### 2. Create the following 10 x 10 ndarray. Which are the squares of the first 100 positive integers.
#### From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [17]:
import numpy as np

# Step 1: Create an array of the first 100 positive integers
first_100_integers = np.arange(1, 101)

# Step 2: Square each of these integers
squares = first_100_integers ** 2

# Step 3: Reshape the array into a 10x10 ndarray
X = squares.reshape((10, 10))

# Step 4: Find the elements divisible by 3
div_by_3 = X[X % 3 == 0]

# Step 5: Save the result as div_by_3.npy
np.save('div_by_3.npy', div_by_3)

# Print the results if you want to see them
print("10x10 Array of Squares:\n", X)
print("\nElements Divisible by 3:\n", div_by_3)


10x10 Array of Squares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
